/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagementsystem;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class reportcard extends javax.swing.JFrame {

    /**
     * Creates new form reportcard
     */
    public reportcard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        studname = new javax.swing.JTextField();
        rollno = new javax.swing.JTextField();
        clas = new javax.swing.JTextField();
        phytotal = new javax.swing.JTextField();
        chemtotal = new javax.swing.JTextField();
        mathtotal = new javax.swing.JTextField();
        phyobt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chemobt = new javax.swing.JTextField();
        mathobt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        jTextField9.setText("jTextField9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(2550, 2490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(studname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 58, 190, 20));

        rollno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, 20));

        clas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(clas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, 20));

        phytotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(phytotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 110, 30));

        chemtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(chemtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 110, 30));

        mathtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(mathtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 110, 30));

        phyobt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        phyobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phyobtActionPerformed(evt);
            }
        });
        getContentPane().add(phyobt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("BACK");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        chemobt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(chemobt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 110, 30));

        mathobt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(mathobt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 110, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("RESULT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 100, -1));

        text.setBackground(new java.awt.Color(153, 153, 255));
        text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        text.setSelectionColor(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 330, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystem/reportimg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 110, 20));

        jLabel4.setText("ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel3.setBackground(new java.awt.Color(166, 197, 207));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 320, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phyobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phyobtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phyobtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "Admin123");
        String sql="insert into reportcard values (?,?,?,?)";
        String p= phyobt.getText();
        double s1= Double.parseDouble(p);
        String m= mathobt.getText();
        double s2= Double.parseDouble(m);
        String c= chemobt.getText();
        double s3= Double.parseDouble(c);
        String pt=phytotal.getText();
        double s4=Double.parseDouble(pt);
        String mt=mathtotal.getText();
        double s5=Double.parseDouble(mt);
        String ct=chemtotal.getText();
        double s6=Double.parseDouble(ct);
        
         double total=((s1+s2+s3)*100)/300;
         
         String grade;
        
        if(total>= 80){
        grade= "A+";
        text.setText("CONGRATULATIOS YOU HAVE PASSED \nYOUR GRADE IS: "+grade);
        }
        else if(total>=70 && total <80){
        grade="A";
        text.setText("CONGRATULATIOS YOU HAVE PASSED \nYOUR GRADE IS: "+grade);
        }
        
        else if(total>=60 && total <70){
        grade="B";
        text.setText("CONGRATULATIOS YOU HAVE PASSED \nYOUR GRADE IS: "+grade);
        }
        
        else if(total>=50 && total <60){
        grade="C";
        text.setText("CONGRATULATIOS YOU HAVE PASSED \nYOUR GRADE IS: "+grade);
        }
        
        else if(total>=40 && total <50){
        grade="D";
        text.setText("CONGRATULATIOS YOU HAVE PASSED \nYOUR GRADE IS: "+grade);
        }
        else
        {   
            grade="Fail";
            text.setText("OOPS! YOU FAILED \nYOUR GRADE IS: "+grade);
        }
        
        
        String n= studname.getText();
        String r=rollno.getText();
        String cla= clas.getText();
        String ph= phyobt.getText();
        String mth= mathobt.getText();
        String cmt= chemobt.getText();
        
        PreparedStatement ptst= conn.prepareStatement(sql);
            ptst.setString(1, id.getText());
            ptst.setString(2, r);
            ptst.setString(3, cla);
            ptst.setString(4, ph);
            ptst.setString(5, mth);
            ptst.setString(6, cmt);
            ptst.setString(7, grade);
            
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data has been saved");
            conn.close();
            }
            
            catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        welcome obj =new welcome();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportcard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chemobt;
    private javax.swing.JTextField chemtotal;
    private javax.swing.JTextField clas;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField mathobt;
    private javax.swing.JTextField mathtotal;
    private javax.swing.JTextField phyobt;
    private javax.swing.JTextField phytotal;
    private javax.swing.JTextField rollno;
    private javax.swing.JTextField studname;
    private javax.swing.JTextPane text;
    // End of variables declaration//GEN-END:variables
}
